export const aiPrompts = {
  receiptParser: `Extract one clean finance record from this receipt. Use the final paid total for amount, merchant for title when visible, ISO date when visible, currency, category, payment method, transactionType, and notes for partial evidence. Never invent missing values. Lower confidence when key fields are uncertain.`,
  bankScreenshotParser: `Extract the most relevant single finance record from this bank or payment screenshot. Capture amount, merchant or counterparty, ISO date, currency, transactionType, payment method, notes, and whether it is a TRANSACTION or DEBT. Never fabricate a merchant, title, or amount.`,
  noteToTransactionParser: `Convert this freeform money note into one structured finance record. Determine whether it is a TRANSACTION or DEBT, capture the exact amount mentioned, infer transactionType when clear, normalize the date if present, and leave unsupported fields empty. Never guess missing amounts or names.`,
  chatDebtParser: `Extract one debt record from this message thread. Include counterpartyName, amount, debtType, due date, notes, and confidence. If the message is not clearly about money owed, keep confidence low and do not guess details.`,
  imageParser: `Analyze this finance-related image and extract one trustworthy structured record only. It may be a receipt, bill, bank screenshot, handwritten note, invoice, or payment app screenshot. Capture title, amount, merchant or counterparty, ISO date when visible, category, paymentMethod, currency, type, transactionType, debtType, notes, and confidence. Do not invent values that are not visible or strongly implied.`,
  expenseCategorizer: `Classify transaction records into meaningful categories for personal and small business finance tracking.`,
  duplicateDetector: `Detect potential duplicates by amount, merchant similarity, date proximity, and attachment similarity. Return confidence score.`,
  monthlySummaryWriter: `Generate a concise and friendly monthly finance summary with key spend categories, debt changes, and actionable reminders.`
};
